# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictures',
            name='picture',
            field=models.ImageField(null=True, upload_to=b''),
        ),
    ]
