# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 02:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0003_pictures_created_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pictures',
            new_name='Picture',
        ),
    ]
